on:
  push:
    paths:
      - 'students/**.md'
  pull_request:
    branches:
      - main
jobs:
  validates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - name: validate-students
        id: validate-students
        run: npm run validate-students
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello world ! :wave:
            ${{ join(steps.validate-students.outputs.*, '\n') }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
